FROM docker:17.10.0-ce-dind

RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk

COPY ./requirements.txt /tmp/

RUN pip3 install -r /tmp/requirements.txt

COPY . .

ENTRYPOINT ["./repro.py"]
